name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
          POSTGRES_DB: etl_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U user -d etl_db"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Check Black version
        run: black --version

      - name: Run lint
        run: make lint   # <-- używamy make, nie ręcznie black/flake8

      - name: Run tests
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
          POSTGRES_DB: etl_db
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5432
        run: make test   # <-- zamiast pytest bezpośrednio
